### PR TITLE
:technologist: Silence test output

### PR DESCRIPTION
**Pull request by homersimpsons**
Reduce test verbosity by removing test output.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I don't understand. This isn't about test output, but about the representer, which doesn't run tests.

**Comment by homersimpsons** [comment]
> I don't understand. This isn't about test output, but about the representer, which doesn't run tests.

The issue is that if specific tests are emmiting diagnosis do stdout (for instance failing tests) it does clutter the ouput instead of showing clearly the actual resuls.

**Comment by ErikSchierboom** [comment]
But this is the representer, not the test runner.

**Comment by homersimpsons** [comment]
> But this is the representer, not the test runner.

Yes, but the modified file is the test runner for the representer

**Comment by ErikSchierboom** [comment]
I see. Sorry for being slow. I would still like to keep the test output though. It can be really helpful when debugging.

**Comment by homersimpsons** [comment]
> I would still like to keep the test output though. It can be really helpful when debugging.

Okay fine this is understandable.

**Pull request closed without merging**
