### PR TITLE
.dockerignore: Document allow list usage

### PR DESCRIPTION
**Pull request by homersimpsons**

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
I have considered doing this before, but people found the allow-list approach to be a lot more confusing. What we could do is add a comment to the bottom of the file explaining the benefits of the allow list.

**Comment by homersimpsons** [comment]
> What we could do is add a comment to the bottom of the file explaining the benefits of the allow list.

I just added a comment, let me know if that is fine like this.

Feel free to close this pull request if you think it is not worth it.

**Comment by ErikSchierboom** [comment]
@homersimpsons I've asked some other people what they think of the change and the majority found the whitelist approach harder to work with. Maybe we can keep the original version and then add some comment about the possibility of using a whitelist and its benefits at the bottom?

**Comment by homersimpsons** [comment]
> Maybe we can keep the original version and then add some comment about the possibility of using a whitelist and its benefits at the bottom?

I did this. I mentioned that some developers find this confusing too. What do you think about the current explanations? Should I make them shorter?

**Pull request merged**
